frr defaults traditional
hostname router-d
service integrated-vtysh-config
!
interface eth0
 ip rip metric-offset 5
!
interface eth1
 ip rip metric-offset 3
!
router rip
 version 2
 no passive-interface default
 network 192.168.8.0/24
 network 192.168.9.0/24
!
