frr defaults traditional
hostname router-b
service integrated-vtysh-config
!
interface eth0
 ip rip metric-offset 1
!
interface eth1
 ip rip metric-offset 2
!
router rip
 version 2
 no passive-interface default
 network 192.168.7.0/24
 network 192.100.0.0/24
!
